fail_fast: true
default_stages: [commit, push, commit-msg]

repos:
  - repo: local
    hooks:
      - id: test
        name: Executing tests
        entry: poetry run pytest --cov-report html --cov-report xml --cov-report term --cov-report annotate --cov=open_note_scanner
        pass_filenames: false
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: sort_imports
        name: Sort library imports
        entry: poetry run isort --force-single-line-imports open_note_scanner tests scripts
        pass_filenames: false
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: black
        name: Black Formatting
        entry: poetry run black open_note_scanner scripts
        pass_filenames: false
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: flake8
        name: Flake8 linting.
        entry: poetry run flake8 --config .flake8 open_note_scanner tests scripts
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: pylint
        name: Pylint linting.
        entry: poetry run pylint open_note_scanner
        language: system
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: export
        name: Export requeriments.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
        always_run: true

  - repo: local
    hooks:
      - id: export-dev
        name: Export requeriments-dev.txt
        language: system
        pass_filenames: false
        entry: poetry export --dev --without-hashes --with-credentials -o requirements-dev.txt
        files: ^(pyproject.toml|poetry.lock)$
        always_run: true

  - repo: local
    hooks:
      - id: bandit
        name: Check for vulnerabilities
        entry: poetry run bandit --exclude "./.venv/*,./test/*,./venv/*" -r -ll .
        pass_filenames: false
        verbose: true
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: safety
        name: Safety
        entry: poetry check
        pass_filenames: false
        language: system
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        always_run: true
      - id: check-case-conflict
        always_run: true
      - id: check-executables-have-shebangs
        always_run: true
      - id: check-json
        always_run: true
      - id: check-merge-conflict
        always_run: true
      - id: check-xml
        always_run: true
      - id: check-yaml
        always_run: true
      - id: detect-private-key
        always_run: true

  - repo: local
    hooks:
      - id: pull
        name: Pull git changes
        entry: git pull
        language: system
        stages:
          - post-commit
