dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# Install dependencies
before_install:
  - python --version
  - uname -a
install:
  - pip install pylint=2.2.2
  - pip install pytest==4.3.1
  - pip install -r requirements.txt
  - pip freeze
# Execute the tests and the linter
script:
  - pytest --cov=open_note_scanner
  - pylint --output-format=text --rcfile=.pylintrc --errors-only open_note_scanner
  - echo "Done"